services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    stop_signal: SIGINT
    volumes:
      - .:/app
    networks:
      back:
      default:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - "5432:5432"
    environment:
      - PGUSER=$POSTGRES_USER
      - PGDATABASE=$POSTGRES_DB
    networks:
      back:
      default:

volumes:
  postgres_data:

networks:
  back:
    driver: bridge
    enable_ipv6: true
    internal: false

  default:
    driver: bridge
