services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    stop_signal: SIGINT
    volumes:
      - ./app:/app
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: