"""deleted sex and age

Revision ID: b670431bdf31
Revises: dec7391fe1aa
Create Date: 2025-07-18 14:37:55.722773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b670431bdf31'
down_revision: Union[str, Sequence[str], None] = 'dec7391fe1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex', schema='klimov')
    op.drop_column('users', 'age', schema='klimov')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True), schema='klimov')
    op.add_column('users', sa.Column('sex', postgresql.ENUM('MALE', 'FEMALE', name='sexenum'), autoincrement=False, nullable=True), schema='klimov')
    # ### end Alembic commands ###
