"""initial rev

Revision ID: dec7391fe1aa
Revises: 1ae927205376
Create Date: 2025-07-18 11:04:07.092628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec7391fe1aa'
down_revision: Union[str, Sequence[str], None] = '1ae927205376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("create schema if not exists klimov")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('surname', sa.String(length=48), nullable=True),
    sa.Column('name', sa.String(length=48), nullable=True),
    sa.Column('patronymic', sa.String(length=48), nullable=True),
    sa.Column('school', sa.Text(), nullable=True),
    sa.Column('grade_number', sa.Integer(), nullable=True),
    sa.Column('grade_letter', sa.String(length=1), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('contact_number', sa.String(length=16), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sexenum'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='klimov'
    )
    op.create_table('answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nature_points', sa.Integer(), nullable=False),
    sa.Column('tech_points', sa.Integer(), nullable=False),
    sa.Column('human_points', sa.Integer(), nullable=False),
    sa.Column('sign_points', sa.Integer(), nullable=False),
    sa.Column('image_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['klimov.users.id'], ),
    sa.PrimaryKeyConstraint('answer_id'),
    schema='klimov'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("drop schema if exists klimov cascade")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers', schema='klimov')
    op.drop_table('users', schema='klimov')
    # ### end Alembic commands ###
